/**
 * API Fixtures — AI 기능 중심 대기업 그룹웨어
 * @generated by ax v0.5
 *
 * 프론트엔드가 실제 응답 구조를 확인하기 위한 예시 데이터.
 * API 응답 구조를 추측하지 말고 이 파일을 참조하세요.
 */

// ─── User ──────────────────────────────────────────────────────────────────

export const userFixture = {
  id: "a1b2c3d4-0000-4000-8000-000000000001",
  name: "김지훈",
  email: "jihun.kim@company.com",
  role: "employee" as const,
  departmentId: "dept-0001-0000-0000-000000000001",
  position: "선임 개발자",
  avatarUrl: null,
  createdAt: "2026-01-15T09:00:00Z",
};

export const adminUserFixture = {
  ...userFixture,
  id: "a1b2c3d4-0000-4000-8000-000000000002",
  name: "이수진",
  email: "sujin.lee@company.com",
  role: "admin" as const,
  position: "시스템 관리자",
};

export const userListFixture = [userFixture, adminUserFixture];
export const emptyUserListFixture: typeof userListFixture = [];

// ─── Department ────────────────────────────────────────────────────────────

export const departmentFixture = {
  id: "dept-0001-0000-0000-000000000001",
  name: "개발팀",
  parentId: "dept-0000-0000-0000-000000000001",
  managerId: "a1b2c3d4-0000-4000-8000-000000000002",
  memberCount: 12,
  createdAt: "2025-03-01T00:00:00Z",
};

export const departmentListFixture = [
  departmentFixture,
  {
    id: "dept-0002-0000-0000-000000000001",
    name: "기획팀",
    parentId: "dept-0000-0000-0000-000000000001",
    managerId: null,
    memberCount: 8,
    createdAt: "2025-03-01T00:00:00Z",
  },
];

// ─── Approval (결재) ───────────────────────────────────────────────────────

export const approvalFixture = {
  id: "appr-0001-0000-4000-800000000001",
  title: "2026년 4월 외부 교육 수강 신청",
  content: "AI 엔지니어링 심화 교육 수강을 위한 결재 요청드립니다.\n교육 기간: 2026.05.10 ~ 2026.05.12\n교육비: 300,000원",
  type: "general" as const,
  status: "pending" as const,
  authorId: "a1b2c3d4-0000-4000-8000-000000000001",
  approvalLine: [
    {
      order: 1,
      userId: "a1b2c3d4-0000-4000-8000-000000000002",
      status: "waiting" as const,
      comment: null,
      processedAt: null,
    },
  ],
  attachments: [{ name: "교육안내서.pdf", url: "https://storage.company.com/files/edu-guide.pdf" }],
  createdAt: "2026-04-16T10:00:00Z",
  updatedAt: "2026-04-16T10:00:00Z",
};

export const approvalListFixture = [approvalFixture];
export const emptyApprovalListFixture: typeof approvalListFixture = [];

export const validationErrorFixture = {
  success: false,
  data: null,
  error: "Validation failed",
  meta: null,
};

// ─── Schedule (일정) ───────────────────────────────────────────────────────

export const scheduleFixture = {
  id: "sched-001-0000-4000-800000000001",
  title: "4월 개발팀 주간 회의",
  description: "개발 진행 현황 공유 및 이슈 논의",
  startAt: "2026-04-17T10:00:00Z",
  endAt: "2026-04-17T11:00:00Z",
  location: "3층 회의실 A",
  isOnline: false,
  organizerId: "a1b2c3d4-0000-4000-8000-000000000001",
  attendees: [
    { userId: "a1b2c3d4-0000-4000-8000-000000000001", status: "accepted" as const },
    { userId: "a1b2c3d4-0000-4000-8000-000000000002", status: "invited" as const },
  ],
  createdAt: "2026-04-14T09:00:00Z",
};

export const scheduleListFixture = [scheduleFixture];
export const emptyScheduleListFixture: typeof scheduleListFixture = [];

// ─── Post (공지사항) ───────────────────────────────────────────────────────

export const postFixture = {
  id: "post-0001-0000-4000-800000000001",
  title: "[필독] 2026년 5월 정기 점검 안내",
  content: "<p>시스템 정기 점검이 아래와 같이 진행됩니다.</p><ul><li>점검 일시: 2026.05.01 02:00 ~ 06:00</li><li>영향 범위: 전체 서비스</li></ul>",
  type: "notice" as const,
  isPinned: true,
  authorId: "a1b2c3d4-0000-4000-8000-000000000002",
  targetDepartments: [],
  attachments: [],
  isRead: false,
  viewCount: 47,
  createdAt: "2026-04-15T08:00:00Z",
};

export const postListFixture = [postFixture];
export const emptyPostListFixture: typeof postListFixture = [];

// ─── AI Session / Query ────────────────────────────────────────────────────

export const aiSessionFixture = {
  id: "sess-0001-0000-4000-800000000001",
  userId: "a1b2c3d4-0000-4000-8000-000000000001",
  title: "결재 대기 현황 조회",
  createdAt: "2026-04-16T09:00:00Z",
  lastMessageAt: "2026-04-16T09:05:00Z",
};

export const aiSessionListFixture = [aiSessionFixture];
export const emptyAISessionListFixture: typeof aiSessionListFixture = [];

export const aiResponseFixture = {
  messageId: "msg-ai-001-0000-4000-800000000001",
  sessionId: "sess-0001-0000-4000-800000000001",
  content: "현재 결재 대기 건은 총 3건입니다:\n1. 외부 교육 수강 신청 (김지훈, 2026-04-16)\n2. 서버 인프라 비용 증설 요청 (박민수, 2026-04-15)\n3. 출장 경비 정산 (이유진, 2026-04-14)",
  sources: [],
  createdAt: "2026-04-16T09:05:10Z",
};

// ─── Notification ──────────────────────────────────────────────────────────

export const notificationFixture = {
  id: "noti-0001-0000-4000-800000000001",
  userId: "a1b2c3d4-0000-4000-8000-000000000002",
  type: "approval" as const,
  title: "새 결재 요청",
  body: "김지훈님이 '2026년 4월 외부 교육 수강 신청' 결재를 요청했습니다.",
  isRead: false,
  relatedId: "appr-0001-0000-4000-800000000001",
  relatedType: "approval",
  createdAt: "2026-04-16T10:00:01Z",
};

export const notificationListFixture = [notificationFixture];
export const emptyNotificationListFixture: typeof notificationListFixture = [];
