/**
 * API 계약 — AI 기능 중심 대기업 그룹웨어
 * @generated by ax v0.5
 *
 * 이 파일은 백엔드와 프론트엔드 간 공유 Zod 스키마를 정의합니다.
 * @source 어노테이션: body=요청 바디, params=URL 경로, query=쿼리 파라미터, cookie=쿠키, server=서버 생성
 */
import { z } from "zod";

// ─── 공통 ──────────────────────────────────────────────────────────────────

export const PaginationSchema = z.object({
  page: z.number().int().min(1).default(1),          // @source query
  limit: z.number().int().min(1).max(100).default(20), // @source query
});

export const ApiResponseSchema = <T extends z.ZodTypeAny>(dataSchema: T) =>
  z.object({
    success: z.boolean(),
    data: dataSchema.nullable(),
    error: z.string().nullable(),
    meta: z
      .object({
        total: z.number(),
        page: z.number(),
        limit: z.number(),
      })
      .nullable(),
  });

// ─── Auth ──────────────────────────────────────────────────────────────────

/**
 * @intent POST /api/auth/login — 이메일/비밀번호 또는 SSO 로그인
 */
export const LoginRequestSchema = z.object({
  email: z.string().email(),    // @source body
  password: z.string().min(8),  // @source body
});

export const LoginResponseSchema = z.object({
  accessToken: z.string(),      // @source server — httpOnly 쿠키로 설정
  user: z.object({
    id: z.string().uuid(),      // @source server
    name: z.string(),           // @source server
    email: z.string().email(),  // @source server
    role: z.enum(["admin", "manager", "employee"]), // @source server
    departmentId: z.string().uuid().nullable(), // @source server
    avatarUrl: z.string().url().nullable(), // @source server
  }),
});

// ─── User ──────────────────────────────────────────────────────────────────

/**
 * @intent 직원 정보 스키마
 */
export const UserSchema = z.object({
  id: z.string().uuid(),         // @source server
  name: z.string().min(1).max(50),
  email: z.string().email(),
  role: z.enum(["admin", "manager", "employee"]),
  departmentId: z.string().uuid().nullable(),
  position: z.string().max(50).nullable(),
  avatarUrl: z.string().url().nullable(),
  createdAt: z.string().datetime(), // @source server
});

export const CreateUserSchema = z.object({
  name: z.string().min(1).max(50),       // @source body
  email: z.string().email(),             // @source body
  role: z.enum(["admin", "manager", "employee"]), // @source body
  departmentId: z.string().uuid(),       // @source body
  position: z.string().max(50).optional(), // @source body
  password: z.string().min(8),           // @source body
});

// ─── Department ────────────────────────────────────────────────────────────

/**
 * @intent 부서/조직 스키마
 */
export const DepartmentSchema = z.object({
  id: z.string().uuid(),             // @source server
  name: z.string().min(1).max(100),
  parentId: z.string().uuid().nullable(),
  managerId: z.string().uuid().nullable(),
  memberCount: z.number().int(),     // @source server
  createdAt: z.string().datetime(),  // @source server
});

export const CreateDepartmentSchema = z.object({
  name: z.string().min(1).max(100),             // @source body
  parentId: z.string().uuid().nullable(),        // @source body
  managerId: z.string().uuid().nullable(),       // @source body
});

// ─── Approval (결재) ───────────────────────────────────────────────────────

/**
 * @intent POST /api/approvals — 결재 기안 제출
 */
export const ApprovalSchema = z.object({
  id: z.string().uuid(),          // @source server
  title: z.string().min(1).max(200),
  content: z.string().min(1),
  type: z.enum(["general", "expense", "vacation", "business_trip", "purchase"]),
  status: z.enum(["pending", "approved", "rejected", "cancelled"]),
  authorId: z.string().uuid(),    // @source server
  approvalLine: z.array(
    z.object({
      order: z.number().int(),
      userId: z.string().uuid(),
      status: z.enum(["waiting", "approved", "rejected"]),
      comment: z.string().nullable(),
      processedAt: z.string().datetime().nullable(),
    })
  ),
  attachments: z.array(z.object({ name: z.string(), url: z.string().url() })),
  createdAt: z.string().datetime(), // @source server
  updatedAt: z.string().datetime(), // @source server
});

export const CreateApprovalSchema = z.object({
  title: z.string().min(1).max(200),           // @source body
  content: z.string().min(1),                  // @source body
  type: z.enum(["general", "expense", "vacation", "business_trip", "purchase"]), // @source body
  approverIds: z.array(z.string().uuid()).min(1), // @source body
  attachments: z.array(
    z.object({ name: z.string(), url: z.string().url() })
  ).optional(), // @source body
});

export const ProcessApprovalSchema = z.object({
  id: z.string().uuid(),                       // @source params
  action: z.enum(["approve", "reject"]),       // @source body
  comment: z.string().max(500).optional(),     // @source body
});

// ─── Schedule (일정) ───────────────────────────────────────────────────────

/**
 * @intent POST /api/schedules — 일정 생성 및 참석자 초대
 */
export const ScheduleSchema = z.object({
  id: z.string().uuid(),                // @source server
  title: z.string().min(1).max(200),
  description: z.string().nullable(),
  startAt: z.string().datetime(),
  endAt: z.string().datetime(),
  location: z.string().max(200).nullable(),
  isOnline: z.boolean().default(false),
  organizerId: z.string().uuid(),       // @source server
  attendees: z.array(
    z.object({
      userId: z.string().uuid(),
      status: z.enum(["invited", "accepted", "declined"]),
    })
  ),
  createdAt: z.string().datetime(),     // @source server
});

export const CreateScheduleSchema = z.object({
  title: z.string().min(1).max(200),             // @source body
  description: z.string().optional(),            // @source body
  startAt: z.string().datetime(),                // @source body
  endAt: z.string().datetime(),                  // @source body
  location: z.string().max(200).optional(),      // @source body
  isOnline: z.boolean().optional(),              // @source body
  attendeeIds: z.array(z.string().uuid()),       // @source body
});

// ─── Post (공지사항/게시글) ────────────────────────────────────────────────

/**
 * @intent POST /api/posts — 공지사항 등록
 */
export const PostSchema = z.object({
  id: z.string().uuid(),            // @source server
  title: z.string().min(1).max(200),
  content: z.string().min(1),
  type: z.enum(["notice", "general"]),
  isPinned: z.boolean().default(false),
  authorId: z.string().uuid(),      // @source server
  targetDepartments: z.array(z.string().uuid()), // [] = 전체
  attachments: z.array(z.object({ name: z.string(), url: z.string().url() })),
  isRead: z.boolean(),              // @source server — 요청자 기준
  viewCount: z.number().int(),      // @source server
  createdAt: z.string().datetime(), // @source server
});

export const CreatePostSchema = z.object({
  title: z.string().min(1).max(200),           // @source body
  content: z.string().min(1),                  // @source body
  type: z.enum(["notice", "general"]),         // @source body
  isPinned: z.boolean().optional(),            // @source body
  targetDepartments: z.array(z.string().uuid()).optional(), // @source body
  attachments: z.array(
    z.object({ name: z.string(), url: z.string().url() })
  ).optional(), // @source body
});

// ─── Message (메시지) ──────────────────────────────────────────────────────

/**
 * @intent POST /api/messages — 메시지 전송
 */
export const MessageSchema = z.object({
  id: z.string().uuid(),            // @source server
  roomId: z.string().uuid(),
  senderId: z.string().uuid(),      // @source server — JWT에서 추출
  content: z.string().min(1).max(5000),
  attachments: z.array(z.object({ name: z.string(), url: z.string().url() })),
  createdAt: z.string().datetime(), // @source server
});

export const CreateMessageSchema = z.object({
  roomId: z.string().uuid(),          // @source body
  content: z.string().min(1).max(5000), // @source body
  attachments: z.array(
    z.object({ name: z.string(), url: z.string().url() })
  ).optional(), // @source body
});

// ─── AI Assistant ──────────────────────────────────────────────────────────

/**
 * @intent POST /api/ai/sessions/:sessionId/messages — AI 질의 전송 (SSE 스트리밍)
 */
export const AISessionSchema = z.object({
  id: z.string().uuid(),              // @source server
  userId: z.string().uuid(),          // @source server
  title: z.string().nullable(),
  createdAt: z.string().datetime(),   // @source server
  lastMessageAt: z.string().datetime().nullable(), // @source server
});

export const AIQuerySchema = z.object({
  sessionId: z.string().uuid(),       // @source params
  content: z.string().min(1).max(2000), // @source body
});

export const AIResponseSchema = z.object({
  messageId: z.string().uuid(),       // @source server
  sessionId: z.string().uuid(),       // @source server
  content: z.string(),
  sources: z.array(
    z.object({
      documentId: z.string().uuid(),
      title: z.string(),
      excerpt: z.string(),
      url: z.string().url().nullable(),
    })
  ),
  createdAt: z.string().datetime(),   // @source server
});

// ─── Notification (알림) ───────────────────────────────────────────────────

/**
 * @intent GET /api/notifications — 사용자 알림 목록
 */
export const NotificationSchema = z.object({
  id: z.string().uuid(),              // @source server
  userId: z.string().uuid(),          // @source server
  type: z.enum(["approval", "schedule", "post", "message", "system"]),
  title: z.string(),
  body: z.string(),
  isRead: z.boolean().default(false),
  relatedId: z.string().uuid().nullable(),
  relatedType: z.string().nullable(),
  createdAt: z.string().datetime(),   // @source server
});

// ─── 타입 추출 ──────────────────────────────────────────────────────────────

export type LoginRequest = z.infer<typeof LoginRequestSchema>;
export type LoginResponse = z.infer<typeof LoginResponseSchema>;
export type User = z.infer<typeof UserSchema>;
export type CreateUser = z.infer<typeof CreateUserSchema>;
export type Department = z.infer<typeof DepartmentSchema>;
export type CreateDepartment = z.infer<typeof CreateDepartmentSchema>;
export type Approval = z.infer<typeof ApprovalSchema>;
export type CreateApproval = z.infer<typeof CreateApprovalSchema>;
export type ProcessApproval = z.infer<typeof ProcessApprovalSchema>;
export type Schedule = z.infer<typeof ScheduleSchema>;
export type CreateSchedule = z.infer<typeof CreateScheduleSchema>;
export type Post = z.infer<typeof PostSchema>;
export type CreatePost = z.infer<typeof CreatePostSchema>;
export type Message = z.infer<typeof MessageSchema>;
export type CreateMessage = z.infer<typeof CreateMessageSchema>;
export type AISession = z.infer<typeof AISessionSchema>;
export type AIQuery = z.infer<typeof AIQuerySchema>;
export type AIResponse = z.infer<typeof AIResponseSchema>;
export type Notification = z.infer<typeof NotificationSchema>;
